name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Docker Compose App to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: SSH into EC2 and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            APP_DIR=~/app-directory
            REPO_URL=https://github.com/Batoolhareb/ML-breast-cancer.git

            if [ ! -d "$APP_DIR" ]; then
              git clone "$REPO_URL" "$APP_DIR"
            fi

            cd "$APP_DIR"

            git fetch origin main
            git reset --hard origin/main
            git clean -fd

            # Build Docker Compose images using the "job" profile
            sudo docker compose --profile job build

            # Run containers in detached mode
            sudo docker compose --profile job up -d
          EOF
