      - name: SSH and deploy
        run: |
          ssh -tt ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e

            APP_DIR=~/app-directory
            REPO_URL=https://github.com/YOUR_USERNAME/YOUR_REPO.git

            mkdir -p \$APP_DIR
            cd \$APP_DIR

            if [ ! -d ".git" ]; then
              git clone \$REPO_URL .
            else
              git pull origin main
            fi

            docker compose down
            docker compose up -d --build

            exit
EOF
