name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          set -xe
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p ${{ secrets.EC2_SSH_PORT || '22' }} -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts || true

      - name: Test SSH connection
        run: |
          set -xe
          ssh -p ${{ secrets.EC2_SSH_PORT || '22' }} \
              -o StrictHostKeyChecking=no \
              -i ~/.ssh/id_rsa \
              ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
              "echo Connected to EC2"

      - name: Deploy Docker Compose app on EC2
        run: |
          ssh -p ${{ secrets.EC2_SSH_PORT || '22' }} \
              -o StrictHostKeyChecking=no \
              -i ~/.ssh/id_rsa \
              ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -xe
            APP_DIR=~/app-directory
            REPO_URL=https://github.com/Batoolhareb/ML-breast-cancer.git

            if [ ! -d "$APP_DIR" ]; then
              git clone "$REPO_URL" "$APP_DIR"
            fi

            cd "$APP_DIR"

            git fetch origin main
            git reset --hard origin/main
            git clean -fd

            sudo docker compose --profile job build
            sudo docker compose --profile job up -d
          EOF
