name: Deploy to AWS EC2 on merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: SSH Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy files to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.EC2_SSH_PORT || '22' }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "mkdir -p ~/app"
        rsync -avz -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.EC2_SSH_PORT || '22' }}" ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/app

    - name: Deploy Docker Compose on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.EC2_SSH_PORT || '22' }} ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/app
          docker-compose down --remove-orphans
          docker-compose up --build -d
        EOF
